import express from 'express';
import supabase from '../../integrations/supabase/supabase.client.mjs';
import { applyScope, requirePermission } from './backoffice.middleware.mjs';
import backofficeStaffService from './backoffice.service.mjs';
import auditBackOffice from './backoffice.audit.mjs';

const router = express.Router();
const leadSelect = 'id,lead_code,contact_id,first_name,last_name,email,phone,source,product_interest,destination,origin,travel_start_date,travel_end_date,estimated_value,status,assigned_agent_id,team_id,priority,next_follow_up_at,created_at,updated_at';
const scopedLeadQuery = (req, base) => applyScope(base, req.staff, backofficeStaffService.scopeFor(req.staff, 'crm.leads.view'));

router.get('/leads', requirePermission('crm.leads.view'), async (req,res,next)=>{ try { let q=supabase.from('crm_leads').select(leadSelect).order('created_at',{ascending:false}); q=scopedLeadQuery(req,q); if(req.query.status) q=q.eq('status',req.query.status); const {data,error}=await q.limit(250); if(error) throw error; res.json({success:true,data:data||[]}); } catch(e){next(e);} });
router.post('/leads', requirePermission('crm.leads.create'), async (req,res,next)=>{ try { const b=req.body||{}; if(!b.firstName||!b.lastName) return res.status(400).json({success:false,error:{code:'INVALID_LEAD',message:'First and last name are required'}}); const assigned=b.assignedAgentId && backofficeStaffService.hasPermission(req.staff,'crm.leads.assign')?b.assignedAgentId:req.staff.id; const payload={lead_code:`L-${Date.now().toString(36).toUpperCase()}`,first_name:b.firstName,last_name:b.lastName,email:b.email||null,phone:b.phone||null,source:b.source||'Manual',product_interest:b.productInterest||'Flight',destination:b.destination||null,origin:b.origin||null,travel_start_date:b.travelStartDate||null,travel_end_date:b.travelEndDate||null,estimated_value:b.estimatedValue||null,status:b.status||'NEW',assigned_agent_id:assigned||null,team_id:req.staff.team?.id||null,priority:b.priority||'NORMAL',next_follow_up_at:b.nextFollowUpAt||null}; const {data,error}=await supabase.from('crm_leads').insert(payload).select(leadSelect).single(); if(error) throw error; await auditBackOffice(req,'lead.created','lead',data.id,{leadCode:data.lead_code}); res.status(201).json({success:true,data}); } catch(e){next(e);} });
router.get('/leads/:id', requirePermission('crm.leads.view'), async (req,res,next)=>{ try { let q=supabase.from('crm_leads').select(leadSelect).eq('id',req.params.id); q=scopedLeadQuery(req,q); const {data,error}=await q.maybeSingle(); if(error) throw error; if(!data) return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Lead not found'}}); res.json({success:true,data}); } catch(e){next(e);} });
router.patch('/leads/:id', requirePermission('crm.leads.edit'), async (req,res,next)=>{ try { const b=req.body||{}; const update={}; const map={firstName:'first_name',lastName:'last_name',email:'email',phone:'phone',source:'source',productInterest:'product_interest',destination:'destination',origin:'origin',travelStartDate:'travel_start_date',travelEndDate:'travel_end_date',estimatedValue:'estimated_value',status:'status',priority:'priority',nextFollowUpAt:'next_follow_up_at'}; Object.entries(map).forEach(([from,to])=>{if(b[from]!==undefined) update[to]=b[from];}); if(b.assignedAgentId!==undefined){ if(!backofficeStaffService.hasPermission(req.staff,'crm.leads.assign')) return res.status(403).json({success:false,error:{code:'FORBIDDEN',message:'Lead assignment permission required'}}); update.assigned_agent_id=b.assignedAgentId; } update.updated_at=new Date().toISOString(); let q=supabase.from('crm_leads').update(update).eq('id',req.params.id); q=applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'crm.leads.view')); const {data,error}=await q.select(leadSelect).maybeSingle(); if(error) throw error; if(!data) return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Lead not found in your scope'}}); await auditBackOffice(req,'lead.updated','lead',data.id,{fields:Object.keys(update)}); res.json({success:true,data}); } catch(e){next(e);} });
router.delete('/leads/:id', requirePermission('crm.leads.delete'), async (req,res,next)=>{ try { let q=supabase.from('crm_leads').delete().eq('id',req.params.id); q=applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'crm.leads.view')); const {data,error}=await q.select('id').maybeSingle(); if(error) throw error; if(!data) return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Lead not found in your scope'}}); await auditBackOffice(req,'lead.deleted','lead',req.params.id); res.json({success:true}); } catch(e){next(e);} });

router.get('/tasks', requirePermission('crm.tasks.view'), async (req,res,next)=>{ try { let q=supabase.from('crm_tasks').select('*').order('due_at',{ascending:true}); q=applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'crm.tasks.view'),{ownerColumn:'assigned_to',teamColumn:'team_id'}); if(req.query.bucket==='today'){const s=new Date();s.setHours(0,0,0,0);const e=new Date(s);e.setDate(e.getDate()+1);q=q.gte('due_at',s.toISOString()).lt('due_at',e.toISOString());} if(req.query.bucket==='overdue')q=q.lt('due_at',new Date().toISOString()).neq('status','COMPLETED'); const {data,error}=await q.limit(250); if(error)throw error; res.json({success:true,data:data||[]}); }catch(e){next(e);} });
router.post('/tasks', requirePermission('crm.tasks.create'), async (req,res,next)=>{ try {const b=req.body||{};if(!b.title)return res.status(400).json({success:false,error:{code:'INVALID_TASK',message:'Task title is required'}});const payload={title:b.title,description:b.description||null,assigned_to:b.assignedTo||req.staff.id||null,team_id:req.staff.team?.id||null,lead_id:b.leadId||null,booking_id:b.bookingId||null,due_at:b.dueAt||null,status:'OPEN',priority:b.priority||'NORMAL',created_by:req.staff.id||null};const {data,error}=await supabase.from('crm_tasks').insert(payload).select('*').single();if(error)throw error;await auditBackOffice(req,'task.created','task',data.id,{leadId:data.lead_id});res.status(201).json({success:true,data});}catch(e){next(e);} });
router.patch('/tasks/:id', requirePermission('crm.tasks.edit'), async (req,res,next)=>{ try {const b=req.body||{};const update={};['title','description','due_at','status','priority','assigned_to'].forEach(k=>{const camel={due_at:'dueAt',assigned_to:'assignedTo'}[k]||k;if(b[camel]!==undefined)update[k]=b[camel];});if(update.status==='COMPLETED')update.completed_at=new Date().toISOString();let q=supabase.from('crm_tasks').update(update).eq('id',req.params.id);q=applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'crm.tasks.view'),{ownerColumn:'assigned_to',teamColumn:'team_id'});const {data,error}=await q.select('*').maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Task not found in your scope'}});await auditBackOffice(req,'task.updated','task',data.id,{fields:Object.keys(update)});res.json({success:true,data});}catch(e){next(e);} });

router.get('/leads/:id/notes', requirePermission('crm.leads.view'), async (req,res,next)=>{ try {let l=supabase.from('crm_leads').select('id').eq('id',req.params.id);l=scopedLeadQuery(req,l);const {data:lead,error:le}=await l.maybeSingle();if(le)throw le;if(!lead)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Lead not found'}});const {data,error}=await supabase.from('crm_notes').select('id,lead_id,author_user_id,body,created_at').eq('lead_id',req.params.id).order('created_at',{ascending:false});if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);} });
router.post('/leads/:id/notes', requirePermission('crm.notes.create'), async (req,res,next)=>{ try {const body=String(req.body?.body||'').trim();if(!body)return res.status(400).json({success:false,error:{code:'INVALID_NOTE',message:'Note text is required'}});let l=supabase.from('crm_leads').select('id').eq('id',req.params.id);l=scopedLeadQuery(req,l);const {data:lead,error:le}=await l.maybeSingle();if(le)throw le;if(!lead)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Lead not found'}});const {data,error}=await supabase.from('crm_notes').insert({lead_id:req.params.id,author_user_id:req.staff.id||null,body}).select('*').single();if(error)throw error;await auditBackOffice(req,'lead.note_created','lead',req.params.id,{noteId:data.id});res.status(201).json({success:true,data});}catch(e){next(e);} });

router.get('/customers', requirePermission('crm.customers.view'), async (req,res,next)=>{ try {let q=supabase.from('crm_leads').select('id,lead_code,first_name,last_name,email,phone,status,destination,travel_start_date,assigned_agent_id,team_id,estimated_value').in('status',['CUSTOMER_APPROVED','PAYMENT_PENDING','PAID','BOOKING_IN_PROGRESS','CONFIRMED','TRAVEL_COMPLETED','REFUNDED']).order('updated_at',{ascending:false});q=applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'crm.customers.view'));const {data,error}=await q.limit(250);if(error)throw error;const seen=new Set();const customers=(data||[]).filter(row=>{const key=(row.email||`${row.first_name}:${row.last_name}`).toLowerCase();if(seen.has(key))return false;seen.add(key);return true;});res.json({success:true,data:customers});}catch(e){next(e);} });

export default router;
export { router as crmRouter };
