import express from 'express';
import supabase from '../../integrations/supabase/supabase.client.mjs';
import{applyScope,requirePermission}from'./backoffice.middleware.mjs';
import backofficeStaffService from'./backoffice.service.mjs';
import auditBackOffice from'./backoffice.audit.mjs';
const router=express.Router();

router.get('/suppliers',requirePermission('suppliers.view'),async(req,res,next)=>{try{const{data,error}=await supabase.from('suppliers').select('*').order('name');if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});
router.post('/suppliers',requirePermission('suppliers.manage'),async(req,res,next)=>{try{const b=req.body||{};if(!b.name||!b.supplierType)return res.status(400).json({success:false,error:{code:'INVALID_SUPPLIER',message:'Name and supplier type are required'}});const payload={name:b.name,supplier_type:b.supplierType,website:b.website||null,account_reference:b.accountReference||null,contact_name:b.contactName||null,contact_email:b.contactEmail||null,contact_phone:b.contactPhone||null,status:b.status||'active',notes:b.notes||null};const{data,error}=await supabase.from('suppliers').insert(payload).select('*').single();if(error)throw error;await auditBackOffice(req,'supplier.created','supplier',data.id,{name:data.name,type:data.supplier_type});res.status(201).json({success:true,data});}catch(e){next(e);}});
router.patch('/suppliers/:id',requirePermission('suppliers.manage'),async(req,res,next)=>{try{const b=req.body||{},update={updated_at:new Date().toISOString()};const map={name:'name',supplierType:'supplier_type',website:'website',accountReference:'account_reference',contactName:'contact_name',contactEmail:'contact_email',contactPhone:'contact_phone',status:'status',notes:'notes'};Object.entries(map).forEach(([a,k])=>{if(b[a]!==undefined)update[k]=b[a];});const{data,error}=await supabase.from('suppliers').update(update).eq('id',req.params.id).select('*').maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Supplier not found'}});await auditBackOffice(req,'supplier.updated','supplier',data.id,{fields:Object.keys(update)});res.json({success:true,data});}catch(e){next(e);}});

router.get('/finance',requirePermission('finance.view'),async(req,res,next)=>{try{const from=req.query.from||new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString();let q=supabase.from('finance_entries').select('*').gte('created_at',from).order('created_at',{ascending:false});q=applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'finance.view'));const{data,error}=await q.limit(500);if(error)throw error;const rows=data||[];const sum=k=>rows.reduce((a,r)=>a+Number(r[k]||0),0);res.json({success:true,data:{summary:{sales:sum('sale_amount'),supplierCost:sum('supplier_cost'),serviceFee:sum('service_fee'),markup:sum('markup'),expectedCommission:sum('expected_commission'),receivedCommission:sum('received_commission'),refunds:sum('refund_amount'),netRevenue:sum('sale_amount')-sum('supplier_cost')+sum('received_commission')-sum('refund_amount')},entries:rows}});}catch(e){next(e);}});
router.post('/finance/entries',requirePermission('finance.view'),async(req,res,next)=>{try{const b=req.body||{};if(!b.bookingType)return res.status(400).json({success:false,error:{code:'INVALID_FINANCE_ENTRY',message:'bookingType is required'}});const payload={booking_type:b.bookingType,booking_ref_id:b.bookingRefId||null,booking_code:b.bookingCode||null,trip_id:b.tripId||null,lead_id:b.leadId||null,assigned_agent_id:b.assignedAgentId||null,team_id:b.teamId||null,supplier_id:b.supplierId||null,sale_amount:Number(b.saleAmount||0),supplier_cost:Number(b.supplierCost||0),service_fee:Number(b.serviceFee||0),markup:Number(b.markup||0),expected_commission:Number(b.expectedCommission||0),received_commission:Number(b.receivedCommission||0),refund_amount:Number(b.refundAmount||0),currency:b.currency||'USD',commission_status:b.commissionStatus||'NOT_APPLICABLE'};const{data,error}=await supabase.from('finance_entries').insert(payload).select('*').single();if(error)throw error;await auditBackOffice(req,'finance.entry_created','finance_entry',data.id,{bookingCode:data.booking_code});res.status(201).json({success:true,data});}catch(e){next(e);}});
router.get('/finance/commissions',requirePermission('finance.commissions'),async(req,res,next)=>{try{const{data,error}=await supabase.from('finance_entries').select('id,booking_type,booking_code,supplier_id,expected_commission,received_commission,currency,commission_status,created_at').neq('commission_status','NOT_APPLICABLE').order('created_at',{ascending:false}).limit(500);if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});
router.get('/finance/supplier-payments',requirePermission('finance.view'),async(req,res,next)=>{try{const{data,error}=await supabase.from('supplier_payments').select('*,suppliers(id,name,supplier_type)').order('due_at',{ascending:true}).limit(500);if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});

router.get('/payments/refunds',requirePermission('payments.view'),async(req,res,next)=>{try{const{data,error}=await supabase.from('refund_requests').select('id,booking_id,amount,currency,reason,status,requested_by,approved_by,processed_by,created_at,approved_at,processed_at').order('created_at',{ascending:false}).limit(250);if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});
router.post('/payments/refunds',requirePermission('payments.refund'),async(req,res,next)=>{try{const b=req.body||{},amount=Number(b.amount||0);if(!b.bookingId||!b.reason||amount<=0)return res.status(400).json({success:false,error:{code:'INVALID_REFUND',message:'bookingId, positive amount and reason are required'}});const setting=await supabase.from('backoffice_settings').select('value').eq('key','refund_large_threshold').maybeSingle();const threshold=Number(setting.data?.value??500);if(amount>threshold&&!backofficeStaffService.hasPermission(req.staff,'payments.refund_large'))return res.status(403).json({success:false,error:{code:'REFUND_APPROVAL_REQUIRED',message:`Refunds above ${threshold} require elevated finance permission`}});const scope=backofficeStaffService.scopeFor(req.staff,'bookings.flights.view')||'ALL';let booking=supabase.from('bookings').select('id,currency,assigned_agent_id,team_id').eq('id',b.bookingId);booking=applyScope(booking,req.staff,scope);const found=await booking.maybeSingle();if(found.error)throw found.error;if(!found.data)return res.status(404).json({success:false,error:{code:'BOOKING_NOT_FOUND',message:'Booking not found in your scope'}});const{data,error}=await supabase.from('refund_requests').insert({booking_id:b.bookingId,amount,currency:b.currency||found.data.currency||'USD',reason:b.reason,requested_by:req.staff.id||null,status:req.staff.legacyOwner?'APPROVED':'REQUESTED',approved_by:req.staff.legacyOwner?req.staff.id:null,approved_at:req.staff.legacyOwner?new Date().toISOString():null}).select('*').single();if(error)throw error;await auditBackOffice(req,'refund.requested','refund',data.id,{bookingId:b.bookingId,amount,currency:data.currency});res.status(201).json({success:true,data});}catch(e){next(e);}});
router.patch('/payments/refunds/:id',requirePermission('payments.refund_large'),async(req,res,next)=>{try{const status=String(req.body?.status||'').toUpperCase();if(!['APPROVED','REJECTED','PROCESSED','CANCELLED'].includes(status))return res.status(400).json({success:false,error:{code:'INVALID_REFUND_STATUS',message:'Unsupported refund status'}});const update={status};if(status==='APPROVED'){update.approved_by=req.staff.id||null;update.approved_at=new Date().toISOString();}if(status==='PROCESSED'){update.processed_by=req.staff.id||null;update.processed_at=new Date().toISOString();}const{data,error}=await supabase.from('refund_requests').update(update).eq('id',req.params.id).select('*').maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Refund request not found'}});await auditBackOffice(req,`refund.${status.toLowerCase()}`,'refund',data.id,{bookingId:data.booking_id,amount:data.amount});res.json({success:true,data});}catch(e){next(e);}});
router.get('/payments/disputes',requirePermission('payments.view'),async(req,res,next)=>{try{const{data,error}=await supabase.from('payment_disputes').select('*').order('created_at',{ascending:false}).limit(250);if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});
export default router;export{router as financeSuppliersRouter};
