import express from 'express';
import supabase from '../../integrations/supabase/supabase.client.mjs';
import { applyScope, requirePermission } from './backoffice.middleware.mjs';
import backofficeStaffService from './backoffice.service.mjs';
import auditBackOffice from './backoffice.audit.mjs';

const router=express.Router();
const flightScope=(req,q)=>applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'bookings.flights.view'));
const leadScope=(req,q)=>applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,'crm.leads.view'));

router.get('/bookings/flights',requirePermission('bookings.flights.view'),async(req,res,next)=>{try{let q=supabase.from('bookings').select('id,confirmation_code,status,payment_status,total_amount,currency,passenger_name,email,phone,lead_id,assigned_agent_id,team_id,trip_id,created_at,updated_at').order('created_at',{ascending:false});q=flightScope(req,q);if(req.query.status)q=q.eq('status',req.query.status);if(req.query.paymentStatus)q=q.eq('payment_status',req.query.paymentStatus);const{data,error}=await q.limit(250);if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});

router.get('/crm/leads/:id/flight-context',requirePermission('bookings.flights.create'),async(req,res,next)=>{try{let q=supabase.from('crm_leads').select('id,lead_code,first_name,last_name,email,phone,origin,destination,travel_start_date,travel_end_date,product_interest,assigned_agent_id,team_id').eq('id',req.params.id);q=leadScope(req,q);const{data,error}=await q.maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Lead not found in your scope'}});const params=new URLSearchParams({leadId:data.id,leadCode:data.lead_code,firstName:data.first_name||'',lastName:data.last_name||'',email:data.email||'',phone:data.phone||'',origin:data.origin||'',destination:data.destination||''});res.json({success:true,data:{lead:data,workflowUrl:`/admin/bookings/new?${params.toString()}`,linkAfterCreateEndpoint:'/api/backoffice/bookings/flights/:bookingId/link'}});}catch(e){next(e);}});

router.patch('/bookings/flights/:bookingId/link',requirePermission('bookings.flights.edit'),async(req,res,next)=>{try{const{leadId,tripId}=req.body||{};let lead=null;if(leadId){let l=supabase.from('crm_leads').select('id,assigned_agent_id,team_id').eq('id',leadId);l=leadScope(req,l);const result=await l.maybeSingle();if(result.error)throw result.error;lead=result.data;if(!lead)return res.status(404).json({success:false,error:{code:'LEAD_NOT_FOUND',message:'Lead not found in your scope'}});}let booking=supabase.from('bookings').select('id,assigned_agent_id,team_id').eq('id',req.params.bookingId);booking=flightScope(req,booking);const current=await booking.maybeSingle();if(current.error)throw current.error;if(!current.data && !req.staff.legacyOwner)return res.status(404).json({success:false,error:{code:'BOOKING_NOT_FOUND',message:'Booking not found in your scope'}});const update={};if(leadId!==undefined)update.lead_id=leadId||null;if(tripId!==undefined)update.trip_id=tripId||null;if(lead){update.assigned_agent_id=lead.assigned_agent_id||req.staff.id||null;update.team_id=lead.team_id||req.staff.team?.id||null;}else if(!current.data?.assigned_agent_id&&req.staff.id){update.assigned_agent_id=req.staff.id;update.team_id=req.staff.team?.id||null;}const{data,error}=await supabase.from('bookings').update(update).eq('id',req.params.bookingId).select('id,confirmation_code,lead_id,assigned_agent_id,team_id,trip_id').single();if(error)throw error;await auditBackOffice(req,'booking.crm_link_updated','booking',data.id,{leadId:data.lead_id,tripId:data.trip_id});res.json({success:true,data});}catch(e){next(e);}});

export default router;
export{router as flightBridgeRouter};
