import express from 'express';
import supabase from '../../integrations/supabase/supabase.client.mjs';
import {applyScope,requirePermission} from './backoffice.middleware.mjs';
import backofficeStaffService from './backoffice.service.mjs';
import auditBackOffice from './backoffice.audit.mjs';
const router=express.Router();
const scoped=(req,q,permission)=>applyScope(q,req.staff,backofficeStaffService.scopeFor(req.staff,permission));
const code=(prefix)=>`${prefix}-${new Date().getFullYear()}-${Date.now().toString(36).toUpperCase()}`;

router.get('/trips',requirePermission('trips.view'),async(req,res,next)=>{try{let q=supabase.from('trips').select('*').order('created_at',{ascending:false});q=scoped(req,q,'trips.view');const{data,error}=await q.limit(250);if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});
router.post('/trips',requirePermission('trips.create'),async(req,res,next)=>{try{const b=req.body||{};if(!b.title)return res.status(400).json({success:false,error:{code:'INVALID_TRIP',message:'Trip title is required'}});const payload={trip_code:code('TRIP'),customer_contact_id:b.customerContactId||null,lead_id:b.leadId||null,assigned_agent_id:b.assignedAgentId||req.staff.id||null,team_id:req.staff.team?.id||null,title:b.title,destination:b.destination||null,start_date:b.startDate||null,end_date:b.endDate||null,status:b.status||'PLANNING'};const{data,error}=await supabase.from('trips').insert(payload).select('*').single();if(error)throw error;await auditBackOffice(req,'trip.created','trip',data.id,{tripCode:data.trip_code});res.status(201).json({success:true,data});}catch(e){next(e);}});
router.get('/trips/:id',requirePermission('trips.view'),async(req,res,next)=>{try{let q=supabase.from('trips').select('*').eq('id',req.params.id);q=scoped(req,q,'trips.view');const{data,error}=await q.maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Trip not found in your scope'}});const[flights,hotels]=await Promise.all([supabase.from('bookings').select('id,confirmation_code,status,payment_status,total_amount,currency').eq('trip_id',data.id),supabase.from('hotel_bookings').select('id,hotel_code,property_name,status,total,currency,check_in,check_out').eq('trip_id',data.id)]);res.json({success:true,data:{...data,items:{flights:flights.data||[],hotels:hotels.data||[]}}});}catch(e){next(e);}});
router.patch('/trips/:id',requirePermission('trips.edit'),async(req,res,next)=>{try{const b=req.body||{},update={updated_at:new Date().toISOString()};const map={title:'title',destination:'destination',startDate:'start_date',endDate:'end_date',status:'status',leadId:'lead_id'};Object.entries(map).forEach(([a,k])=>{if(b[a]!==undefined)update[k]=b[a];});let q=supabase.from('trips').update(update).eq('id',req.params.id);q=scoped(req,q,'trips.view');const{data,error}=await q.select('*').maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Trip not found in your scope'}});await auditBackOffice(req,'trip.updated','trip',data.id,{fields:Object.keys(update)});res.json({success:true,data});}catch(e){next(e);}});

router.get('/bookings/hotels',requirePermission('bookings.hotels.view'),async(req,res,next)=>{try{let q=supabase.from('hotel_bookings').select('*').order('created_at',{ascending:false});q=scoped(req,q,'bookings.hotels.view');if(req.query.status)q=q.eq('status',req.query.status);const{data,error}=await q.limit(250);if(error)throw error;res.json({success:true,data:data||[]});}catch(e){next(e);}});
router.post('/bookings/hotels',requirePermission('bookings.hotels.create'),async(req,res,next)=>{try{const b=req.body||{};if(!b.destination||!b.propertyName||!b.checkIn||!b.checkOut)return res.status(400).json({success:false,error:{code:'INVALID_HOTEL',message:'Destination, property, check-in and check-out are required'}});const rate=Number(b.rate||0),fees=Number(b.taxesFees||0);const payload={hotel_code:code('HTL'),trip_id:b.tripId||null,lead_id:b.leadId||null,customer_contact_id:b.customerContactId||null,assigned_agent_id:b.assignedAgentId||req.staff.id||null,team_id:req.staff.team?.id||null,destination:b.destination,property_name:b.propertyName,supplier_name:b.supplierName||null,check_in:b.checkIn,check_out:b.checkOut,rooms:Number(b.rooms||1),adults:Number(b.adults||1),children:Number(b.children||0),room_type:b.roomType||null,supplier_confirmation_number:b.supplierConfirmationNumber||null,rate,taxes_fees:fees,total:b.total!==undefined?Number(b.total):rate+fees,currency:b.currency||'USD',payment_status:b.paymentStatus||'pending',cancellation_policy:b.cancellationPolicy||null,cancellation_deadline:b.cancellationDeadline||null,status:b.status||'REQUESTED',commission_percentage:b.commissionPercentage||null,expected_commission:b.expectedCommission||null,actual_commission:b.actualCommission||null,commission_status:b.commissionStatus||'NOT_APPLICABLE',notes:b.notes||null};const{data,error}=await supabase.from('hotel_bookings').insert(payload).select('*').single();if(error)throw error;await auditBackOffice(req,'hotel.created','hotel_booking',data.id,{hotelCode:data.hotel_code});res.status(201).json({success:true,data});}catch(e){next(e);}});
router.get('/bookings/hotels/:id',requirePermission('bookings.hotels.view'),async(req,res,next)=>{try{let q=supabase.from('hotel_bookings').select('*').eq('id',req.params.id);q=scoped(req,q,'bookings.hotels.view');const{data,error}=await q.maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Hotel booking not found in your scope'}});res.json({success:true,data});}catch(e){next(e);}});
router.patch('/bookings/hotels/:id',requirePermission('bookings.hotels.edit'),async(req,res,next)=>{try{const b=req.body||{},update={updated_at:new Date().toISOString()};const allowed=['trip_id','lead_id','destination','property_name','supplier_name','check_in','check_out','rooms','adults','children','room_type','supplier_confirmation_number','rate','taxes_fees','total','currency','payment_status','cancellation_policy','cancellation_deadline','status','commission_percentage','expected_commission','actual_commission','commission_status','notes'];for(const key of allowed){const camel=key.replace(/_([a-z])/g,(_,c)=>c.toUpperCase());if(b[camel]!==undefined)update[key]=b[camel];}let q=supabase.from('hotel_bookings').update(update).eq('id',req.params.id);q=scoped(req,q,'bookings.hotels.view');const{data,error}=await q.select('*').maybeSingle();if(error)throw error;if(!data)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Hotel booking not found in your scope'}});await auditBackOffice(req,'hotel.updated','hotel_booking',data.id,{fields:Object.keys(update)});res.json({success:true,data});}catch(e){next(e);}});
export default router;export{router as tripsHotelsRouter};
