import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { boGet, boPatch, boPost } from './backofficeApi';
import { useBackOfficeAuth } from './BackOfficeAuthContext';

const money = (value, currency = 'USD') => new Intl.NumberFormat('en-US', { style: 'currency', currency: currency || 'USD' }).format(Number(value || 0));
const date = value => value ? new Date(value).toLocaleString() : '—';

function useResource(path) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const reload = useCallback(async () => { setLoading(true); setError(''); try { setData(await boGet(path)); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [path]);
  useEffect(() => { reload(); }, [reload]);
  return { data, loading, error, reload };
}

function Header({ title, subtitle, actions }) { return <div className="bo-page-header"><div><h1>{title}</h1>{subtitle && <div className="bo-muted">{subtitle}</div>}</div>{actions && <div className="bo-actions">{actions}</div>}</div>; }
function State({ loading, error, empty }) { if (loading) return <div className="bo-card">Loading…</div>; if (error) return <div className="bo-card bo-error">{error}</div>; if (empty) return <div className="bo-card bo-muted">No records found.</div>; return null; }
function Table({ columns, rows }) { return <div className="bo-table-wrap"><table className="bo-table"><thead><tr>{columns.map(c=><th key={c.label}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id || row.lead_code || row.trip_code || row.confirmation_code || index}>{columns.map(c=><td key={c.label}>{c.render ? c.render(row) : (row[c.key] ?? '—')}</td>)}</tr>)}</tbody></table></div>; }
function FormActions({ saving, label = 'Save' }) { return <div className="bo-actions"><button className="bo-button" disabled={saving}>{saving ? 'Saving…' : label}</button></div>; }

export function DashboardPage() {
  const { profile } = useBackOfficeAuth(); const { data, loading, error } = useResource('/dashboard/summary');
  const metrics = data?.metrics || {}; const finance = data?.finance;
  return <><Header title="Dashboard" subtitle={`${profile?.roleName || profile?.role}${profile?.team?.name ? ` · ${profile.team.name}` : ''}`} />
    <State loading={loading} error={error} />
    {!loading && !error && <><div className="bo-grid">{Object.entries(metrics).map(([key,value])=><div className="bo-card bo-kpi" key={key}><span className="bo-muted">{key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</span><strong>{value}</strong></div>)}</div>{finance && <div className="bo-card"><h2>Finance this month</h2><div className="bo-grid">{Object.entries(finance).map(([key,value])=><div className="bo-kpi" key={key}><span className="bo-muted">{key.replace(/([A-Z])/g,' $1')}</span><strong>{money(value)}</strong></div>)}</div></div>}</>}
  </>;
}

export function LeadsPage() {
  const { data, loading, error, reload } = useResource('/crm/leads'); const { hasPermission } = useBackOfficeAuth();
  const [showForm,setShowForm]=useState(false); const [saving,setSaving]=useState(false); const [form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',origin:'',destination:'',productInterest:'Flight',priority:'NORMAL'}); const [formError,setFormError]=useState('');
  const submit=async e=>{e.preventDefault();setSaving(true);setFormError('');try{await boPost('/crm/leads',form);setForm({firstName:'',lastName:'',email:'',phone:'',origin:'',destination:'',productInterest:'Flight',priority:'NORMAL'});setShowForm(false);await reload();}catch(err){setFormError(err.message);}finally{setSaving(false);}};
  const rows=data||[];
  return <><Header title="Leads" subtitle="Sales pipeline with server-enforced ownership scope" actions={hasPermission('crm.leads.create') && <button className="bo-button" onClick={()=>setShowForm(v=>!v)}>{showForm?'Close':'New Lead'}</button>} />
    {showForm && <form className="bo-card bo-form" onSubmit={submit}><h2>New lead</h2>{formError&&<div className="bo-error">{formError}</div>}<div className="bo-form-grid"><input required placeholder="First name" value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><input required placeholder="Last name" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><input type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Origin" value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}/><input placeholder="Destination" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/><select value={form.productInterest} onChange={e=>setForm({...form,productInterest:e.target.value})}><option>Flight</option><option>Hotel</option><option>Car</option><option>Package</option></select><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></div><FormActions saving={saving} label="Create Lead" /></form>}
    <State loading={loading} error={error} empty={!loading&&!error&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{label:'Lead',render:r=><Link to={`/admin/crm/leads/${r.id}`}>{r.lead_code}</Link>},{label:'Customer',render:r=>`${r.first_name} ${r.last_name}`},{key:'product_interest',label:'Product'},{key:'origin',label:'Origin'},{key:'destination',label:'Destination'},{key:'status',label:'Status'},{key:'priority',label:'Priority'},{label:'Follow-up',render:r=>date(r.next_follow_up_at)}]} />}
  </>;
}

export function LeadDetailPage() {
  const { id }=useParams(); const { data:lead,loading,error,reload }=useResource(`/crm/leads/${id}`); const notes=useResource(`/crm/leads/${id}/notes`); const activity=useResource(`/crm/leads/${id}/activity`); const {hasPermission}=useBackOfficeAuth(); const[note,setNote]=useState('');const[actionError,setActionError]=useState('');const[saving,setSaving]=useState(false);
  const addNote=async e=>{e.preventDefault();if(!note.trim())return;setSaving(true);setActionError('');try{await boPost(`/crm/leads/${id}/notes`,{body:note});setNote('');await Promise.all([notes.reload(),activity.reload(),reload()]);}catch(err){setActionError(err.message);}finally{setSaving(false);}};
  const createFlight=async()=>{setActionError('');try{const ctx=await boGet(`/crm/leads/${id}/flight-context`);window.location.assign(ctx.workflowUrl);}catch(err){setActionError(err.message);}};
  return <><Header title={lead?`${lead.lead_code} · ${lead.first_name} ${lead.last_name}`:'Lead Details'} subtitle={lead?`${lead.status} · ${lead.product_interest}`:''} actions={<><Link className="bo-button secondary" to="/admin/crm/leads">Back to leads</Link>{hasPermission('bookings.flights.create')&&<button className="bo-button" onClick={createFlight}>Create Flight Booking</button>}</>} /><State loading={loading} error={error}/>{actionError&&<div className="bo-card bo-error">{actionError}</div>}{lead&&<div className="bo-grid"><div className="bo-card"><h2>Contact</h2><p>{lead.email||'—'}<br/>{lead.phone||'—'}</p></div><div className="bo-card"><h2>Travel</h2><p>{lead.origin||'—'} → {lead.destination||'—'}<br/>{lead.travel_start_date||'Dates not set'}</p></div><div className="bo-card"><h2>Sales</h2><p>Status: <strong>{lead.status}</strong><br/>Priority: {lead.priority}<br/>Estimated: {money(lead.estimated_value)}</p></div></div>}
    <div className="bo-two-col"><div className="bo-card"><h2>Notes</h2>{hasPermission('crm.notes.create')&&<form onSubmit={addNote}><textarea rows="3" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a customer or sales note"/><FormActions saving={saving} label="Add Note" /></form>}<div className="bo-list">{(notes.data||[]).map(n=><div key={n.id}><strong>{date(n.created_at)}</strong><div>{n.body}</div></div>)}</div></div><div className="bo-card"><h2>Activity</h2><div className="bo-list">{(activity.data||[]).map((item,index)=><div key={`${item.type}-${index}`}><strong>{date(item.at)}</strong><div>{item.label}</div>{item.actor&&<small>{item.actor}</small>}</div>)}</div></div></div>
  </>;
}

export function CustomersPage(){const r=useResource('/crm/customers');const rows=r.data||[];return <><Header title="Customers" subtitle="Customer view derived from qualified/approved CRM relationships"/><State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{label:'Customer',render:x=>`${x.first_name} ${x.last_name}`},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'destination',label:'Destination'},{key:'status',label:'Latest Stage'},{label:'Value',render:x=>money(x.estimated_value)}]}/>}</>}

export function TasksPage(){const r=useResource('/crm/tasks');const{hasPermission}=useBackOfficeAuth();const[title,setTitle]=useState('');const[dueAt,setDueAt]=useState('');const[error,setError]=useState('');const submit=async e=>{e.preventDefault();try{await boPost('/crm/tasks',{title,dueAt:dueAt||null});setTitle('');setDueAt('');await r.reload();}catch(err){setError(err.message);}};const complete=async id=>{try{await boPatch(`/crm/tasks/${id}`,{status:'COMPLETED'});await r.reload();}catch(err){setError(err.message);}};const rows=r.data||[];return <><Header title="Tasks & Follow-ups" subtitle="My, team or all tasks according to role scope"/>{hasPermission('crm.tasks.create')&&<form className="bo-card bo-inline-form" onSubmit={submit}>{error&&<div className="bo-error">{error}</div>}<input required placeholder="Task title" value={title} onChange={e=>setTitle(e.target.value)}/><input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/><button className="bo-button">Add Task</button></form>}<State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{key:'title',label:'Task'},{key:'priority',label:'Priority'},{key:'status',label:'Status'},{label:'Due',render:x=>date(x.due_at)},{label:'Action',render:x=>x.status!=='COMPLETED'&&hasPermission('crm.tasks.edit')?<button className="bo-link-button" onClick={()=>complete(x.id)}>Complete</button>:'—'}]}/>}</>}

export function TripsPage(){const r=useResource('/trips');const{hasPermission}=useBackOfficeAuth();const[form,setForm]=useState({title:'',destination:'',startDate:'',endDate:''});const[err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{await boPost('/trips',form);setForm({title:'',destination:'',startDate:'',endDate:''});await r.reload();}catch(x){setErr(x.message);}};const rows=r.data||[];return <><Header title="Trips" subtitle="Parent journeys connecting flights, hotels and cars"/>{hasPermission('trips.create')&&<form className="bo-card bo-inline-form" onSubmit={submit}>{err&&<div className="bo-error">{err}</div>}<input required placeholder="Trip title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Destination" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/><input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/><input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/><button className="bo-button">Create Trip</button></form>}<State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{label:'Trip',render:x=><Link to={`/admin/trips/${x.id}`}>{x.trip_code}</Link>},{key:'title',label:'Title'},{key:'destination',label:'Destination'},{key:'status',label:'Status'},{key:'start_date',label:'Start'},{key:'end_date',label:'End'}]}/>}</>}
export function TripDetailPage(){const{id}=useParams();const r=useResource(`/trips/${id}`);return <><Header title={r.data?.trip_code||'Trip Details'} subtitle={r.data?.title} actions={<Link className="bo-button secondary" to="/admin/trips">Back</Link>}/><State loading={r.loading} error={r.error}/>{r.data&&<><div className="bo-card"><strong>{r.data.destination||'Destination not set'}</strong> · {r.data.start_date||'—'} to {r.data.end_date||'—'} · {r.data.status}</div><div className="bo-two-col"><div className="bo-card"><h2>Flights</h2>{(r.data.items?.flights||[]).map(x=><div key={x.id}><Link to={`/admin/bookings/flights/${x.confirmation_code}`}>{x.confirmation_code}</Link> · {x.status}</div>)}</div><div className="bo-card"><h2>Hotels</h2>{(r.data.items?.hotels||[]).map(x=><div key={x.id}><Link to={`/admin/bookings/hotels/${x.id}`}>{x.property_name}</Link> · {x.status}</div>)}</div></div></>}</>}

export function FlightBookingsPage(){const r=useResource('/bookings/flights');const rows=r.data||[];return <><Header title="Flight Bookings" subtitle="Stable production flight editor reused inside the back office" actions={<Link className="bo-button" to="/admin/bookings/new">Create Flight Booking</Link>}/><State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{label:'Booking',render:x=><Link to={`/admin/bookings/flights/${x.confirmation_code}`}>{x.confirmation_code}</Link>},{key:'passenger_name',label:'Passenger'},{key:'status',label:'Booking Status'},{key:'payment_status',label:'Payment'},{label:'Total',render:x=>money(x.total_amount,x.currency)},{label:'Created',render:x=>date(x.created_at)}]}/>}</>}

function ProductBookingPage({type}){const plural=type==='hotel'?'hotels':'cars';const permission=`bookings.${plural}.create`;const r=useResource(`/bookings/${plural}`);const{hasPermission}=useBackOfficeAuth();const initial=type==='hotel'?{destination:'',propertyName:'',checkIn:'',checkOut:'',total:''}:{pickupLocation:'',dropoffLocation:'',pickupAt:'',dropoffAt:'',customerTotal:''};const[form,setForm]=useState(initial);const[err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{await boPost(`/bookings/${plural}`,form);setForm(initial);await r.reload();}catch(x){setErr(x.message);}};const rows=r.data||[];return <><Header title={type==='hotel'?'Hotel Bookings':'Car Bookings'} subtitle="Manual / semi-automated operations module"/>{hasPermission(permission)&&<form className="bo-card bo-form" onSubmit={submit}><h2>New {type} request</h2>{err&&<div className="bo-error">{err}</div>}<div className="bo-form-grid">{type==='hotel'?<><input required placeholder="Destination" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/><input required placeholder="Property name" value={form.propertyName} onChange={e=>setForm({...form,propertyName:e.target.value})}/><input required type="date" value={form.checkIn} onChange={e=>setForm({...form,checkIn:e.target.value})}/><input required type="date" value={form.checkOut} onChange={e=>setForm({...form,checkOut:e.target.value})}/><input type="number" step="0.01" placeholder="Customer total" value={form.total} onChange={e=>setForm({...form,total:e.target.value})}/></>:<><input required placeholder="Pickup location" value={form.pickupLocation} onChange={e=>setForm({...form,pickupLocation:e.target.value})}/><input required placeholder="Dropoff location" value={form.dropoffLocation} onChange={e=>setForm({...form,dropoffLocation:e.target.value})}/><input required type="datetime-local" value={form.pickupAt} onChange={e=>setForm({...form,pickupAt:e.target.value})}/><input required type="datetime-local" value={form.dropoffAt} onChange={e=>setForm({...form,dropoffAt:e.target.value})}/><input type="number" step="0.01" placeholder="Customer total" value={form.customerTotal} onChange={e=>setForm({...form,customerTotal:e.target.value})}/></>}</div><FormActions saving={false} label={`Create ${type==='hotel'?'Hotel':'Car'} Request`}/></form>}<State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={type==='hotel'?[{key:'hotel_code',label:'ID'},{key:'property_name',label:'Property'},{key:'destination',label:'Destination'},{key:'check_in',label:'Check-in'},{key:'status',label:'Status'},{label:'Total',render:x=>money(x.total,x.currency)}]:[{key:'car_code',label:'ID'},{key:'pickup_location',label:'Pickup'},{key:'dropoff_location',label:'Dropoff'},{label:'Pickup Time',render:x=>date(x.pickup_at)},{key:'status',label:'Status'},{label:'Total',render:x=>money(x.customer_total,x.currency)}]}/>}</>}
export const HotelsPage=()=> <ProductBookingPage type="hotel"/>; export const CarsPage=()=> <ProductBookingPage type="car"/>;
export function ProductBookingDetailPage({type}){const{id}=useParams();const plural=type==='hotel'?'hotels':'cars';const r=useResource(`/bookings/${plural}/${id}`);return <><Header title={`${type==='hotel'?'Hotel':'Car'} Booking`} actions={<Link className="bo-button secondary" to={`/admin/bookings/${plural}`}>Back</Link>}/><State loading={r.loading} error={r.error}/>{r.data&&<div className="bo-card bo-detail-grid">{Object.entries(r.data).filter(([key])=>!['assigned_agent_id','team_id','supplier_id'].includes(key)).map(([key,value])=><div key={key}><span>{key.replaceAll('_',' ')}</span><strong>{value===null||value===''?'—':String(value)}</strong></div>)}</div>}</>}

export function PaymentsPage(){const r=useResource('/payments');const rows=r.data||[];return <><Header title="Customer Payments" subtitle="Status only; payment credentials and raw card data are never exposed"/><State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{key:'confirmation_code',label:'Booking'},{key:'passenger_name',label:'Customer'},{key:'payment_status',label:'Payment Status'},{key:'status',label:'Booking Status'},{label:'Amount',render:x=>money(x.total_amount,x.currency)},{key:'payment_details',label:'Payment Data'}]}/>}</>}
export function RefundsPage(){const r=useResource('/payments/refunds');const{hasPermission}=useBackOfficeAuth();const[form,setForm]=useState({bookingId:'',amount:'',reason:''});const[err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{await boPost('/payments/refunds',form);setForm({bookingId:'',amount:'',reason:''});await r.reload();}catch(x){setErr(x.message);}};const rows=r.data||[];return <><Header title="Refunds" subtitle="Threshold and approval rules are enforced by the backend"/>{hasPermission('payments.refund')&&<form className="bo-card bo-inline-form" onSubmit={submit}>{err&&<div className="bo-error">{err}</div>}<input required placeholder="Booking UUID" value={form.bookingId} onChange={e=>setForm({...form,bookingId:e.target.value})}/><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input required placeholder="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button className="bo-button">Request Refund</button></form>}<State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{key:'booking_id',label:'Booking'},{label:'Amount',render:x=>money(x.amount,x.currency)},{key:'reason',label:'Reason'},{key:'status',label:'Status'},{label:'Created',render:x=>date(x.created_at)}]}/>}</>}
export function DisputesPage(){const r=useResource('/payments/disputes');const rows=r.data||[];return <><Header title="Disputes"/><State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{key:'provider_reference',label:'Provider Ref'},{key:'booking_id',label:'Booking'},{label:'Amount',render:x=>money(x.amount,x.currency)},{key:'status',label:'Status'},{key:'reason',label:'Reason'},{label:'Due',render:x=>date(x.due_at)}]}/>}</>}

export function FinancePage(){const r=useResource('/finance');const summary=r.data?.summary;return <><Header title="Finance" subtitle="Role-limited revenue, markup and commission foundation"/><State loading={r.loading} error={r.error}/>{summary&&<div className="bo-grid">{Object.entries(summary).map(([key,value])=><div className="bo-card bo-kpi" key={key}><span className="bo-muted">{key.replace(/([A-Z])/g,' $1')}</span><strong>{money(value)}</strong></div>)}</div>}</>}
export function CommissionsPage(){const r=useResource('/finance/commissions');const rows=r.data||[];return <><Header title="Commissions"/><State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{key:'booking_code',label:'Booking'},{key:'booking_type',label:'Type'},{label:'Expected',render:x=>money(x.expected_commission,x.currency)},{label:'Received',render:x=>money(x.received_commission,x.currency)},{key:'commission_status',label:'Status'}]}/>}</>}
export function SupplierPaymentsPage(){const r=useResource('/finance/supplier-payments');const rows=r.data||[];return <><Header title="Supplier Payments"/><State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{label:'Supplier',render:x=>x.suppliers?.name||'—'},{label:'Amount',render:x=>money(x.amount,x.currency)},{key:'status',label:'Status'},{label:'Due',render:x=>date(x.due_at)},{key:'reference',label:'Reference'}]}/>}</>}

export function SuppliersPage(){const r=useResource('/suppliers');const{hasPermission}=useBackOfficeAuth();const[form,setForm]=useState({name:'',supplierType:'HOTEL',contactEmail:''});const[err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{await boPost('/suppliers',form);setForm({name:'',supplierType:'HOTEL',contactEmail:''});await r.reload();}catch(x){setErr(x.message);}};const rows=r.data||[];return <><Header title="Suppliers" subtitle="Registry only—credentials and API secrets remain server-side"/>{hasPermission('suppliers.manage')&&<form className="bo-card bo-inline-form" onSubmit={submit}>{err&&<div className="bo-error">{err}</div>}<input required placeholder="Supplier name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.supplierType} onChange={e=>setForm({...form,supplierType:e.target.value})}><option>AIR</option><option>HOTEL</option><option>CAR</option><option>CRUISE</option><option>ACTIVITY</option><option>HOST_AGENCY</option><option>OTHER</option></select><input type="email" placeholder="Contact email" value={form.contactEmail} onChange={e=>setForm({...form,contactEmail:e.target.value})}/><button className="bo-button">Add Supplier</button></form>}<State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{key:'name',label:'Supplier'},{key:'supplier_type',label:'Type'},{key:'status',label:'Status'},{key:'contact_name',label:'Contact'},{key:'contact_email',label:'Email'},{key:'account_reference',label:'Account Ref'}]}/>}</>}

export function ReportsPage(){const r=useResource('/reports');return <><Header title="Reports" subtitle="Server-scoped operational and finance summary"/><State loading={r.loading} error={r.error}/>{r.data&&<div className="bo-two-col">{r.data.leads&&<div className="bo-card"><h2>Leads</h2><p>Total: <strong>{r.data.leads.total}</strong></p><p>Estimated pipeline: <strong>{money(r.data.leads.estimatedPipeline)}</strong></p>{Object.entries(r.data.leads.byStatus||{}).map(([k,v])=><div key={k}>{k}: {v}</div>)}</div>}{r.data.finance&&<div className="bo-card"><h2>Finance</h2>{Object.entries(r.data.finance).map(([k,v])=><div key={k}>{k.replace(/([A-Z])/g,' $1')}: <strong>{money(v)}</strong></div>)}</div>}</div>}</>}

export function TeamPage(){const users=useResource('/team/users');const roles=useResource('/team/roles');const teams=useResource('/team/teams');const{hasPermission}=useBackOfficeAuth();const[form,setForm]=useState({name:'',email:'',password:'',roleId:'',teamId:''});const[err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{await boPost('/team/users',form);setForm({name:'',email:'',password:'',roleId:'',teamId:''});await users.reload();}catch(x){setErr(x.message);}};const roleMap=useMemo(()=>Object.fromEntries((roles.data||[]).map(x=>[x.id,x.name])),[roles.data]);return <><Header title="Team" subtitle="Users, roles and teams" actions={<div className="bo-actions"><Link className="bo-button secondary" to="/admin/team/roles">Roles</Link><Link className="bo-button secondary" to="/admin/team/teams">Teams</Link></div>}/>{hasPermission('team.manage')&&<form className="bo-card bo-form" onSubmit={submit}><h2>Add staff user</h2>{err&&<div className="bo-error">{err}</div>}<div className="bo-form-grid"><input required placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="10" type="password" placeholder="Temporary password (10+ chars)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select required value={form.roleId} onChange={e=>setForm({...form,roleId:e.target.value})}><option value="">Select role</option>{(roles.data||[]).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select value={form.teamId} onChange={e=>setForm({...form,teamId:e.target.value})}><option value="">No team</option>{(teams.data||[]).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></div><FormActions saving={false} label="Create Staff User"/></form>}<State loading={users.loading} error={users.error} empty={!users.loading&&!(users.data||[]).length}/>{(users.data||[]).length>0&&<Table rows={users.data} columns={[{key:'name',label:'Name'},{key:'email',label:'Email'},{label:'Role',render:x=>x.role?.name||roleMap[x.role_id]||'—'},{label:'Team',render:x=>x.team?.name||'—'},{key:'status',label:'Status'},{label:'Last Login',render:x=>date(x.last_login_at)}]}/>}</>}
export function RolesPage(){const roles=useResource('/team/roles');const rows=roles.data||[];return <><Header title="Roles & Permissions" subtitle="Permission grants are backend-backed; owner role is protected" actions={<Link className="bo-button secondary" to="/admin/team/users">Users</Link>}/><State loading={roles.loading} error={roles.error} empty={!roles.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{key:'name',label:'Role'},{key:'key',label:'Key'},{key:'description',label:'Purpose'}]}/>}</>}
export function TeamsPage(){const r=useResource('/team/teams');const{hasPermission}=useBackOfficeAuth();const[name,setName]=useState('');const[err,setErr]=useState('');const submit=async e=>{e.preventDefault();try{await boPost('/team/teams',{name});setName('');await r.reload();}catch(x){setErr(x.message);}};return <><Header title="Teams" actions={<Link className="bo-button secondary" to="/admin/team/users">Users</Link>}/>{hasPermission('team.manage')&&<form className="bo-card bo-inline-form" onSubmit={submit}>{err&&<div className="bo-error">{err}</div>}<input required placeholder="Team name" value={name} onChange={e=>setName(e.target.value)}/><button className="bo-button">Add Team</button></form>}<State loading={r.loading} error={r.error} empty={!r.loading&&!(r.data||[]).length}/>{(r.data||[]).length>0&&<Table rows={r.data} columns={[{key:'name',label:'Team'},{key:'status',label:'Status'}]}/>}</>}

export function AuditLogsPage(){const r=useResource('/settings/audit-logs');const rows=r.data||[];return <><Header title="Audit Logs" subtitle="Append-only operational activity; sensitive payment details are excluded"/><State loading={r.loading} error={r.error} empty={!r.loading&&!rows.length}/>{rows.length>0&&<Table rows={rows} columns={[{label:'Time',render:x=>date(x.created_at)},{key:'actor',label:'Actor'},{key:'action',label:'Action'},{key:'entity_type',label:'Entity'},{key:'entity_id',label:'Entity ID'},{key:'ip_address',label:'IP'}]}/>}</>}
export function IntegrationsPage(){const r=useResource('/settings/integrations');return <><Header title="Integrations"/><State loading={r.loading} error={r.error}/>{r.data&&<div className="bo-card"><h2>Server-only credentials</h2><p>{r.data.message}</p><p>Secrets exposed to frontend: <strong>{String(r.data.secretsExposed)}</strong></p></div>}</>}
export function SecurityPage(){const r=useResource('/settings/security');return <><Header title="Security"/><State loading={r.loading} error={r.error}/>{r.data&&<div className="bo-card bo-detail-grid">{Object.entries(r.data).map(([k,v])=><div key={k}><span>{k.replace(/([A-Z])/g,' $1')}</span><strong>{Array.isArray(v)?v.join(', '):String(v)}</strong></div>)}</div>}</>}
export function SettingsPage(){return <><Header title="Admin / Settings"/><div className="bo-grid"><Link className="bo-card bo-module-link" to="/admin/settings/integrations"><strong>Integrations</strong><span>Owner-only, secrets remain server-side</span></Link><Link className="bo-card bo-module-link" to="/admin/settings/security"><strong>Security</strong><span>RBAC and security posture</span></Link><Link className="bo-card bo-module-link" to="/admin/settings/audit-logs"><strong>Audit Logs</strong><span>Critical operational activity</span></Link></div></>}
export function PlaceholderPage({title,description}){return <><Header title={title} subtitle={description}/><div className="bo-card">This operational view is connected to the shared back-office shell and permission model. Product-specific automation can be added without changing the stable flight module.</div></>}
