import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { boGet, boPost } from './backofficeApi';
import { useBackOfficeAuth } from './BackOfficeAuthContext';

const money = (value, currency = 'USD') => { try { return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(Number(value || 0)); } catch { return `${currency} ${Number(value || 0).toFixed(2)}`; } };
const fmtDate = value => value ? new Date(value).toLocaleString() : '—';
const remaining = value => { if (!value) return 'Unavailable'; const ms = new Date(value).getTime() - Date.now(); if (ms <= 0) return 'Expired'; const h = Math.floor(ms / 3600000); const m = Math.floor((ms % 3600000) / 60000); return `${h}h ${m}m`; };

function loadScript(src) { return new Promise((resolve, reject) => { const existing = document.querySelector(`script[src="${src}"]`); if (existing) { if (window.VGSShow) return resolve(); existing.addEventListener('load', resolve, { once: true }); existing.addEventListener('error', reject, { once: true }); return; } const script = document.createElement('script'); script.src = src; script.async = true; script.onload = resolve; script.onerror = () => reject(new Error('VGS secure reveal library could not be loaded.')); document.head.appendChild(script); }); }
function Header({ title, subtitle, actions }) { return <div className="bo-page-header"><div><h1>{title}</h1>{subtitle && <div className="bo-muted">{subtitle}</div>}</div>{actions && <div className="bo-actions">{actions}</div>}</div>; }
function ErrorBox({ message }) { return message ? <div className="bo-card bo-error">{message}</div> : null; }
function badge(status) { return <span className={`secure-payment-status secure-payment-status--${String(status || '').toLowerCase()}`}>{status || '—'}</span>; }

export function PaymentAuthorizationsPage() {
  const { hasPermission } = useBackOfficeAuth();
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [showForm, setShowForm] = useState(false); const [createdUrl, setCreatedUrl] = useState('');
  const [form, setForm] = useState({ entityType: 'FLIGHT', entityCode: '', customerName: '', customerEmail: '', customerPhone: '', authorizedAmount: '', currency: 'USD', purpose: '' });
  const reload = async () => { setLoading(true); setError(''); try { setRows(await boGet('/payments/authorizations') || []); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { reload(); }, []);
  const submit = async e => { e.preventDefault(); setError(''); setCreatedUrl(''); try { const result = await boPost('/payments/authorizations', form); setCreatedUrl(result.publicUrl); setShowForm(false); await reload(); } catch (x) { setError(x.message); } };
  return <>
    <Header title="Payment Authorizations" subtitle="Reusable secure card authorization for flights, hotels, cars, cruises and future travel products" actions={hasPermission('payments.authorization.manage') && <button className="bo-button" onClick={() => setShowForm(v => !v)}>{showForm ? 'Close' : 'New Authorization'}</button>} />
    <ErrorBox message={error} />
    {createdUrl && <div className="bo-card"><strong>Secure customer link created</strong><div className="secure-payment-created-link"><input readOnly value={createdUrl} /><button className="bo-button" onClick={() => navigator.clipboard?.writeText(createdUrl)}>Copy Link</button></div><div className="bo-muted">The raw link token is shown here only after creation. Sending a new link rotates the token.</div></div>}
    {showForm && <form className="bo-card bo-form" onSubmit={submit}><h2>Create secure payment authorization</h2><div className="bo-form-grid"><select value={form.entityType} onChange={e => setForm({ ...form, entityType: e.target.value })}>{['FLIGHT','HOTEL','CAR','CRUISE','TOUR','ACTIVITY','PACKAGE','INSURANCE','TRIP','OTHER'].map(x => <option key={x}>{x}</option>)}</select><input placeholder="Booking / product reference" value={form.entityCode} onChange={e => setForm({ ...form, entityCode: e.target.value })} /><input required placeholder="Customer name" value={form.customerName} onChange={e => setForm({ ...form, customerName: e.target.value })} /><input required type="email" placeholder="Customer email" value={form.customerEmail} onChange={e => setForm({ ...form, customerEmail: e.target.value })} /><input placeholder="Customer phone" value={form.customerPhone} onChange={e => setForm({ ...form, customerPhone: e.target.value })} /><input required type="number" min="0.01" step="0.01" placeholder="Maximum authorized amount" value={form.authorizedAmount} onChange={e => setForm({ ...form, authorizedAmount: e.target.value })} /><input required placeholder="Currency" maxLength="3" value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value.toUpperCase() })} /><input required placeholder="Purpose, e.g. JFK → DEL airfare" value={form.purpose} onChange={e => setForm({ ...form, purpose: e.target.value })} /></div><div className="bo-actions"><button className="bo-button">Create Secure Link</button></div></form>}
    <div className="bo-card"><div className="bo-table-wrap"><table className="bo-table"><thead><tr><th>Authorization</th><th>Product</th><th>Customer</th><th>Maximum</th><th>Card</th><th>CVV</th><th>Status</th><th>Created</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><Link to={`/admin/payments/authorizations/${row.id}`}>{row.authorizationCode}</Link><div className="bo-muted">{row.context?.entityCode || row.context?.contextCode}</div></td><td>{row.context?.entityType}</td><td>{row.customerName}<div className="bo-muted">{row.customerEmail}</div></td><td>{money(row.authorizedAmount, row.currency)}</td><td>{row.paymentMethod?.last4 ? `${String(row.paymentMethod.cardBrand || 'Card').toUpperCase()} •••• ${row.paymentMethod.last4}` : row.paymentMethod?.panStatus === 'AVAILABLE' ? 'Secure card on file' : 'Not collected'}</td><td>{row.paymentMethod?.cvvStatus || 'NOT_COLLECTED'}{row.paymentMethod?.cvvExpiresAt && <div className="bo-muted">{remaining(row.paymentMethod.cvvExpiresAt)}</div>}</td><td>{badge(row.status)}</td><td>{fmtDate(row.createdAt)}</td></tr>)}{!loading && !rows.length && <tr><td colSpan="8" className="bo-muted">No secure payment authorizations yet.</td></tr>}</tbody></table></div>{loading && <div className="bo-muted">Loading authorizations…</div>}</div>
  </>;
}

function SecureReveal({ authorizationId, secureToken, vault, onEnd }) {
  const framesRef = useRef([]); const [error, setError] = useState('');
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        if (!vault?.configured || !vault?.showScript) throw new Error('VGS Show is not configured for this vault.');
        await loadScript(vault.showScript);
        if (cancelled || !window.VGSShow) return;
        let show = window.VGSShow.create(vault.vaultId, () => {}).setEnvironment(vault.environment);
        if (vault.showCname) show = show.setCname(vault.showCname);
        const authToken = localStorage.getItem('token');
        const headers = { Authorization: `Bearer ${authToken}`, 'X-TFS-Secure-Session': secureToken };
        const create = (field, selector, label) => {
          const frame = show.request({ name: `tfs-${field}`, method: 'GET', path: `/api/backoffice/payments/authorizations/${authorizationId}/reveal?field=${field}`, headers, htmlWrapper: 'text', jsonPathSelector: 'json.value' });
          frame.render(selector, { 'font-family': 'Inter, Arial, sans-serif', 'font-size': '16px', color: '#18263a', 'font-weight': '650', padding: '10px' });
          const copy = show.copyFrom(frame, { text: `Copy ${label}` }, () => {}); copy.render(`${selector}-copy`, { 'font-family': 'Inter, Arial, sans-serif', 'font-size': '12px', color: '#fff', background: '#861b3d', padding: '8px 11px', border: '0', 'border-radius': '7px', cursor: 'pointer' });
          framesRef.current.push(frame, copy);
        };
        create('pan', '#tfs-show-pan', 'card number'); create('expiration', '#tfs-show-expiration', 'expiration'); create('cvv', '#tfs-show-cvv', 'CVV');
      } catch (e) { if (!cancelled) setError(e.message); }
    })();
    return () => { cancelled = true; for (const frame of framesRef.current) { try { frame.unmount?.(); } catch { /* best effort */ } } framesRef.current = []; };
  }, [authorizationId, secureToken, vault]);
  return <div className="bo-card secure-reveal-card"><div className="secure-reveal-header"><div><h2>Secure payment method</h2><div className="bo-muted">Sensitive values render inside VGS-controlled iframes. They are not placed in React state.</div></div><button className="bo-button secondary" onClick={onEnd}>End Secure Session</button></div>{error && <div className="bo-error">{error}</div>}<div className="secure-reveal-grid"><div><span>Card number</span><div id="tfs-show-pan" className="secure-show-frame"/><div id="tfs-show-pan-copy"/></div><div><span>Expiration</span><div id="tfs-show-expiration" className="secure-show-frame"/><div id="tfs-show-expiration-copy"/></div><div><span>CVV</span><div id="tfs-show-cvv" className="secure-show-frame"/><div id="tfs-show-cvv-copy"/></div></div></div>;
}

export function PaymentAuthorizationDetailPage() {
  const { id } = useParams(); const { hasPermission } = useBackOfficeAuth();
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [publicUrl, setPublicUrl] = useState('');
  const [otpSession, setOtpSession] = useState(null); const [otp, setOtp] = useState(''); const [secureToken, setSecureToken] = useState(''); const [secureExpiresAt, setSecureExpiresAt] = useState(null);
  const [charge, setCharge] = useState({ supplierName: '', amount: '', currency: 'USD', status: 'AUTHORIZED', providerReference: '' });
  const reload = async () => { setLoading(true); setError(''); try { setData(await boGet(`/payments/authorizations/${id}`)); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { reload(); }, [id]);
  useEffect(() => { if (!secureExpiresAt) return; const timer = setInterval(() => { if (new Date(secureExpiresAt).getTime() <= Date.now()) { setSecureToken(''); setSecureExpiresAt(null); } }, 1000); return () => clearInterval(timer); }, [secureExpiresAt]);
  const auth = data?.authorization; const method = auth?.paymentMethod;
  const sendLink = async () => { try { const result = await boPost(`/payments/authorizations/${id}/send`, {}); setPublicUrl(result.publicUrl); } catch (e) { setError(e.message); } };
  const recollect = async sendEmail => { try { const result = await boPost(`/payments/authorizations/${id}/recollect`, { sendEmail }); setPublicUrl(result.publicUrl); await reload(); } catch (e) { setError(e.message); } };
  const requestOtp = async () => { try { const result = await boPost(`/payments/authorizations/${id}/access/request-otp`, { reason: 'Supplier booking / ticketing' }); setOtpSession(result); setOtp(''); } catch (e) { setError(e.message); } };
  const verifyOtp = async e => { e.preventDefault(); try { const result = await boPost(`/payments/authorizations/${id}/access/verify-otp`, { accessSessionId: otpSession.accessSessionId, otp }); setSecureToken(result.secureSessionToken); setSecureExpiresAt(result.expiresAt); setOtpSession(null); setOtp(''); } catch (x) { setError(x.message); } };
  const endSecure = async () => { try { if (secureToken) await fetch(`/api/backoffice/payments/authorizations/${id}/access/end`, { method: 'POST', headers: { Authorization: `Bearer ${localStorage.getItem('token')}`, 'Content-Type': 'application/json', 'X-TFS-Secure-Session': secureToken }, body: '{}' }); } finally { setSecureToken(''); setSecureExpiresAt(null); } };
  const addCharge = async e => { e.preventDefault(); try { await boPost(`/payments/authorizations/${id}/supplier-charges`, charge); setCharge({ supplierName: '', amount: '', currency: auth?.currency || 'USD', status: 'AUTHORIZED', providerReference: '' }); await reload(); } catch (x) { setError(x.message); } };
  const cvvRemaining = useMemo(() => remaining(method?.cvvExpiresAt), [method?.cvvExpiresAt]);
  if (loading) return <div className="bo-card">Loading secure payment authorization…</div>;
  if (!auth) return <ErrorBox message={error || 'Authorization not found.'}/>;
  return <>
    <Header title={auth.authorizationCode} subtitle={`${auth.context?.entityType || 'TRAVEL'} · ${auth.context?.entityCode || auth.context?.contextCode || ''}`} actions={<><Link className="bo-button secondary" to="/admin/payments/authorizations">Back</Link>{hasPermission('payments.authorization.manage') && <button className="bo-button" onClick={sendLink}>Send New Link</button>}</>} />
    <ErrorBox message={error}/>
    {publicUrl && <div className="bo-card"><strong>Latest customer link</strong><div className="secure-payment-created-link"><input readOnly value={publicUrl}/><button className="bo-button" onClick={() => navigator.clipboard?.writeText(publicUrl)}>Copy</button></div></div>}
    <div className="bo-grid"><div className="bo-card bo-kpi"><span className="bo-muted">Authorized maximum</span><strong>{money(auth.authorizedAmount, auth.currency)}</strong></div><div className="bo-card bo-kpi"><span className="bo-muted">Authorization</span><strong>{auth.status}</strong></div><div className="bo-card bo-kpi"><span className="bo-muted">CVV status</span><strong>{method?.cvvStatus || 'NOT_COLLECTED'}</strong></div><div className="bo-card bo-kpi"><span className="bo-muted">CVV remaining</span><strong>{cvvRemaining}</strong></div></div>
    <div className="bo-two-col"><div className="bo-card"><h2>Customer & purpose</h2><p><strong>{auth.customerName}</strong><br/>{auth.customerEmail}<br/>{auth.customerPhone || '—'}</p><p>{auth.purpose}</p><p className="bo-muted">Authorized at {fmtDate(auth.authorizedAt)}</p></div><div className="bo-card"><h2>Vaulted payment method</h2><p>{method?.last4 ? `${String(method.cardBrand || 'Card').toUpperCase()} •••• ${method.last4}` : method?.panStatus === 'AVAILABLE' ? 'Secure card on file' : 'Not collected'}</p><p>PAN: <strong>{method?.panStatus || 'NOT_COLLECTED'}</strong><br/>CVV: <strong>{method?.cvvStatus || 'NOT_COLLECTED'}</strong><br/>CVV expiry: {fmtDate(method?.cvvExpiresAt)}</p>{auth.vault?.configured ? <div className="bo-muted">VGS {auth.vault.environment} · requested CVV TTL {auth.vault.targetCvvTtlHours}h · {auth.vault.cvvTtlConfirmed ? 'provider-confirmed' : 'NOT confirmed'}</div> : <div className="bo-error">VGS vault credentials are not configured.</div>}</div></div>
    <div className="bo-card"><h2>Secure credential access</h2>{!hasPermission('payments.secure_card_access') ? <div className="bo-muted">Your role can see masked payment metadata but cannot reveal secure credentials.</div> : !method?.panStatus || method.panStatus !== 'AVAILABLE' ? <div className="bo-muted">The customer has not submitted a secure card yet.</div> : secureToken ? <><div className="secure-access-timer">MFA session active until {fmtDate(secureExpiresAt)}</div><SecureReveal authorizationId={id} secureToken={secureToken} vault={auth.vault} onEnd={endSecure}/></> : otpSession ? <form className="bo-inline-form" onSubmit={verifyOtp}><input required inputMode="numeric" maxLength="6" placeholder="6-digit OTP" value={otp} onChange={e => setOtp(e.target.value.replace(/\D/g, '').slice(0,6))}/><button className="bo-button">Verify & Open Secure Card</button><div className="bo-muted">Code sent to {otpSession.destination}; expires {fmtDate(otpSession.expiresAt)}.</div></form> : <button className="bo-button" onClick={requestOtp}>Access Secure Card with OTP</button>}</div>
    {hasPermission('payments.authorization.manage') && method?.panStatus === 'AVAILABLE' && <div className="bo-card"><h2>CVV lifecycle</h2><p className="bo-muted">A CVV is volatile. When it expires or after the related supplier transaction is authorized, request a fresh CVV rather than retaining the old value.</p><div className="bo-actions"><button className="bo-button secondary" onClick={() => recollect(false)}>Create CVV Recollection Link</button><button className="bo-button" onClick={() => recollect(true)}>Email CVV Recollection Link</button></div></div>}
    {hasPermission('payments.supplier_charge') && <form className="bo-card bo-form" onSubmit={addCharge}><h2>Record supplier transaction</h2><div className="bo-form-grid"><input required placeholder="Supplier" value={charge.supplierName} onChange={e => setCharge({ ...charge, supplierName: e.target.value })}/><input required type="number" min="0.01" step="0.01" placeholder="Amount" value={charge.amount} onChange={e => setCharge({ ...charge, amount: e.target.value })}/><input required placeholder="Currency" maxLength="3" value={charge.currency || auth.currency} onChange={e => setCharge({ ...charge, currency: e.target.value.toUpperCase() })}/><select value={charge.status} onChange={e => setCharge({ ...charge, status: e.target.value })}><option>AUTHORIZED</option><option>PENDING</option><option>PROCESSING</option><option>DECLINED</option><option>FAILED</option><option>VOIDED</option><option>REFUNDED</option></select><input placeholder="Supplier / processor reference" value={charge.providerReference} onChange={e => setCharge({ ...charge, providerReference: e.target.value })}/></div><p className="bo-muted">Marking the transaction AUTHORIZED triggers deletion of the volatile CVV alias. If VGS deletion fails, the CRM records DELETION_PENDING for follow-up.</p><button className="bo-button">Record Transaction</button></form>}
    <div className="bo-two-col"><div className="bo-card"><h2>Supplier transactions</h2><div className="bo-list">{(data.supplierCharges || []).map(item => <div key={item.id}><strong>{item.supplier_name || 'Supplier'} · {money(item.amount, item.currency)}</strong><div>{item.status}{item.provider_reference ? ` · ${item.provider_reference}` : ''}</div><small>{fmtDate(item.created_at)} · {item.attempted_by_email || 'Owner'}</small></div>)}{!data.supplierCharges?.length && <div className="bo-muted">No supplier transactions yet.</div>}</div></div><div className="bo-card"><h2>Secure access audit</h2><div className="bo-list">{(data.accessEvents || []).map(item => <div key={item.id}><strong>{item.event_type}</strong><div>{item.reason || ''}</div><small>{fmtDate(item.created_at)} · {item.staff_email || 'system'}</small></div>)}{!data.accessEvents?.length && <div className="bo-muted">No secure access activity yet.</div>}</div></div></div>
  </>;
}
